### ISSUE TITLE
real vs paper scale

### ISSUE THREAD

**Issue by Neon22** [Moini/inkscape-realscale-extension#2]
In order to label a value as 12km but not to make an image that actual size. How about adding a drawing scale factor as well.
So user can indicate distance is 12km. Then also indicate that scale is 1:100000 - which will make it 12cm across. Or perhaps 1:500000 which would make it 2.4cm long. A precalculation (not sure its possible) would indicate if this scaled the bounds of the drawing off the page.

Then you can print this paper scale as well. So users know that measurements taken off the drawing are to what scale.
Common scales are different for Architects and Engineers but you could offer a dropdown:
- https://en.wikipedia.org/wiki/Architect's_scale
- https://en.wikipedia.org/wiki/Engineer's_scale
- http://www.draftingsteals.com/catalog-drafting---drawing-aides-scales.html

Of course the crazy US still in inches which adds weird scales to those in "common" use.
http://www.aaadrafting.com/drafting-tools-techniques/engineeringscales.html

*For inches*
1:1, 1:2, 1:4, 1:8, 1:16, 1:24, 1:32, 1:48, 1:64, 1:96, 1:128
*For metric*
1:1, 1:10, 1:5, 1:50, 1:10, 1:100, 1:20, 1:200, 1:1250, 1:2500
1:2, 1:20, 1:500, 1:1000
1:25, 1:250, 1:331⁄3

Here's the number in a list for copy/paste
[1, 2, 4, 5, 8, 10, 16, 24, 25, 32, 33.333, 48, 50, 64, 96, 100, 128, 200, 250, 500, 1000, 1250, 2500]
with these two as non-preferred
[25, 33.333]

Factors of 100 times these for the Km problem :)
But here is another list organised by usage:
- http://www.engineeringtoolbox.com/scaling-blueprint-drawings-d_1704.html

Here are some reference pictures of how the scale factor is normally drawn:
- http://engineeringtraining.tpub.com/14069/css/14069_78.htm
- http://survivalcommonsense.com/miller-map-scalesfeed/
- http://draftingmanuals.tpub.com/14276/css/14276_61.htm
-  http://flylib.com/books/2/332/1/html/2/images/f16vs04.jpg
  - from http://flylib.com/books/en/2.332.1.103/1/
I.e in words   "Scale 1:NNNN"
and as a rect with alternating filled/unfilled blocks showing 2x the distance with the first half divided into 10, or 5 or whatever is the full decimal division for a neat dwg.

Related topic - Check out how cool this is:
- http://www.blocklayer.com/scale-rule.aspx

**Comment by Moini** [comment]
Phew, that's quite a few improvement suggestions... ;-) Thank you for trying it out, and thinking about how to make this thing better!

They all make sense to me. Only I don't have the time currently to work on this, and I already have difficulties resolving the problem with the placement of the up-/downscaled parts...  Before I add anything new, that should be fixed first. So please be patient! :)

**Comment by Neon22** [comment]
Had a go at fixing the scale around a useful point problem.
Looks at the straightline and assumes that one end or the other is the best place to scale the drawing around.
So checks page quadrants to try to keep drawing inside page in most useful way.
And so calcs the scaling center.

Then scale is applied by transforming objects to 0,0, then scaling, then transforming back.
Works pretty well I think...?

**Comment by Moini** [comment]
I'll take a close look next week, as even with explanations, it will take me some time to grasp what you did :) Thanks!

**Comment by Neon22** [comment]
hoping your subscribed to: https://bugs.launchpad.net/inkscape-web/+bug/1572394
where discussion about extensions and website

**Comment by Moini** [comment]
Yes, of course I am :) (as a member of inkscape-web, I'd have to actively unsubscribe ;-) )

**Comment by Moini** [comment]
(maybe I should tell you that Hachmann and Moini are the same... :-) )

**Comment by Neon22** [comment]
I think you succeeded here. well done :)

**Comment by Moini** [comment]
?! Wasn't me who did the work, I think ;-) Thank you, Neon22!

**Comment by Moini** [comment]
(and thanks for patiently answering my questions!)
